
-- Dirt Monster by PilzAdam

mobs:register_mob("mobs:dirt_monster", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	reach = 2,
	damage = 2,
	hp_min = 15,
	hp_max = 16,
	armor = 100,
	collisionbox = {-0.4, -1, -0.4, 0.4, 0.8, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {
		{"mobs_dirt_monster.png"},
	},
	blood_texture = "default_dirt.png",
	makes_footstep_sound = true,
	sounds = {
		random = "mobs_dirtmonster",
	},
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	jump = true,
	drops = {
		{name = "default:dirt",
		chance = 5, min = 1, max = 5},
		{name = "default:dirt_jungle",
		chance = 15, min = 0, max = 5},
		{name = "default:dirt_deep",
		chance = 15, min = 0, max = 5},
		{name = "default:dirt_med",
		chance = 15, min = 0, max = 5},
		{name = "farming:seed_onion",
		chance = 60, min = 0, max = 5},
		{name = "farming:seed_tomato",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_mushroom",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_salad",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_potato",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_strawberry",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_ananas",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_corn",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_pepper",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_carrot",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_beens",
		chance = 60, min = 0, max = 3},
		{name = "farming:seed_cotton",
		chance = 45, min = 0, max = 3},
		{name = "farming:seed_wheat",
		chance = 35, min = 1, max = 3},
		
	},
	water_damage = 1,
	lava_damage = 5,
	light_damage = 2,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})

mobs:register_spawn("mobs:dirt_monster", {"default:dirt_with_grass", "default:dirt_med_with_grass", "ethereal:gray_dirt"}, 5, 0, 7000, 2, 31000)
mobs:register_spawn("mobs:dirt_monster", {"default:dirt_with_grass", "default:dirt_med_with_grass" }, 3, 0, 3000, 5, 31000)

mobs:register_egg("mobs:dirt_monster", "Dirt Monster", "default_dirt.png", 1)